"""
Constants for customer service.
Reduces code duplication and improves maintainability.
"""

# Event publishing error messages
PUBLISH_ERROR_RABBITMQ_FALSE = "RabbitMQ publish returned False"
PUBLISH_ERROR_PUBLISHER_NONE = "EventPublisher connection is None"

# Event statuses
EVENT_STATUS_PENDING = "pending"
EVENT_STATUS_PUBLISHED = "published"
EVENT_STATUS_FAILED = "failed"
EVENT_STATUS_DELIVERED = "delivered"

# Delivery statuses
DELIVERY_STATUS_PENDING = "pending"
DELIVERY_STATUS_DELIVERED = "delivered"
DELIVERY_STATUS_FAILED = "failed"

# Customer statuses
CUSTOMER_STATUS_ACTIVE = "ACTIVE"
CUSTOMER_STATUS_INACTIVE = "INACTIVE"
CUSTOMER_STATUS_PENDING_AML = "PENDING_AML"
CUSTOMER_STATUS_BLOCKED = "BLOCKED"

# Valid customer status transitions
CUSTOMER_STATUS_TRANSITIONS = {
    CUSTOMER_STATUS_PENDING_AML: [CUSTOMER_STATUS_ACTIVE, CUSTOMER_STATUS_BLOCKED],
    CUSTOMER_STATUS_ACTIVE: [CUSTOMER_STATUS_INACTIVE, CUSTOMER_STATUS_BLOCKED],
    CUSTOMER_STATUS_INACTIVE: [CUSTOMER_STATUS_ACTIVE, CUSTOMER_STATUS_BLOCKED],
    CUSTOMER_STATUS_BLOCKED: [CUSTOMER_STATUS_ACTIVE],  # Admin unblock only
}

# Event types
EVENT_TYPE_CUSTOMER_CREATION = "customer_creation"
EVENT_TYPE_CUSTOMER_DELETION = "customer_deletion"
EVENT_TYPE_CUSTOMER_STATUS_CHANGE = "customer_status_change"
EVENT_TYPE_CUSTOMER_BLOCKED_AML = "customer_blocked_aml"
EVENT_TYPE_CONSUMER_CREATED = "consumer_created"
